# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WtyczkaProjekt
                                 A QGIS plugin
 1. Liczene przewyższeń  2. Liczenie pola powierzchni metodą Gaussa
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-02
        copyright            : (C) 2023 by Nina Janczak Jan Sychowiec
        email                : nina.janczak.stud@pw.edu.pl jan.sychowiec.stud@pw.edu.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load WtyczkaProjekt class from file WtyczkaProjekt.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .wtyczka_projekt import WtyczkaProjekt
    return WtyczkaProjekt(iface)
