# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\jansy\OneDrive\Pulpit\4_sem\Informatyka_II\projekt_2_informatyka\wtyczka_projekt\wtyczka_projekt_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WtyczkaProjektDialogBase(object):
    def setupUi(self, WtyczkaProjektDialogBase):
        WtyczkaProjektDialogBase.setObjectName("WtyczkaProjektDialogBase")
        WtyczkaProjektDialogBase.resize(847, 482)
        self.button_box = QtWidgets.QDialogButtonBox(WtyczkaProjektDialogBase)
        self.button_box.setGeometry(QtCore.QRect(400, 400, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.tytul = QtWidgets.QTextBrowser(WtyczkaProjektDialogBase)
        self.tytul.setGeometry(QtCore.QRect(0, 10, 851, 51))
        self.tytul.setObjectName("tytul")
        self.wybor_warstwy = QgsMapLayerComboBox(WtyczkaProjektDialogBase)
        self.wybor_warstwy.setGeometry(QtCore.QRect(140, 70, 571, 31))
        self.wybor_warstwy.setEditable(True)
        self.wybor_warstwy.setObjectName("wybor_warstwy")
        self.klik_przewyzszenie = QtWidgets.QPushButton(WtyczkaProjektDialogBase)
        self.klik_przewyzszenie.setGeometry(QtCore.QRect(80, 170, 141, 41))
        self.klik_przewyzszenie.setObjectName("klik_przewyzszenie")
        self.klik_pole = QtWidgets.QPushButton(WtyczkaProjektDialogBase)
        self.klik_pole.setGeometry(QtCore.QRect(80, 320, 141, 41))
        self.klik_pole.setObjectName("klik_pole")
        self.line = QtWidgets.QFrame(WtyczkaProjektDialogBase)
        self.line.setGeometry(QtCore.QRect(-20, 260, 871, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2punkty = QtWidgets.QLabel(WtyczkaProjektDialogBase)
        self.label_2punkty.setGeometry(QtCore.QRect(50, 130, 101, 16))
        self.label_2punkty.setObjectName("label_2punkty")
        self.label_3punkty = QtWidgets.QLabel(WtyczkaProjektDialogBase)
        self.label_3punkty.setGeometry(QtCore.QRect(50, 280, 161, 16))
        self.label_3punkty.setObjectName("label_3punkty")
        self.line_2 = QtWidgets.QFrame(WtyczkaProjektDialogBase)
        self.line_2.setGeometry(QtCore.QRect(0, 110, 871, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_wynik_przewyzszenie = QtWidgets.QLabel(WtyczkaProjektDialogBase)
        self.label_wynik_przewyzszenie.setGeometry(QtCore.QRect(310, 170, 471, 31))
        self.label_wynik_przewyzszenie.setText("")
        self.label_wynik_przewyzszenie.setObjectName("label_wynik_przewyzszenie")
        self.label_wyni_pole = QtWidgets.QLabel(WtyczkaProjektDialogBase)
        self.label_wyni_pole.setGeometry(QtCore.QRect(310, 320, 481, 31))
        self.label_wyni_pole.setText("")
        self.label_wyni_pole.setObjectName("label_wyni_pole")

        self.retranslateUi(WtyczkaProjektDialogBase)
        self.button_box.rejected.connect(WtyczkaProjektDialogBase.reject) # type: ignore
        self.button_box.accepted.connect(WtyczkaProjektDialogBase.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(WtyczkaProjektDialogBase)

    def retranslateUi(self, WtyczkaProjektDialogBase):
        _translate = QtCore.QCoreApplication.translate
        WtyczkaProjektDialogBase.setWindowTitle(_translate("WtyczkaProjektDialogBase", "Operacje na punktach"))
        self.tytul.setHtml(_translate("WtyczkaProjektDialogBase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Wtyczka do wykonywania operacji w programie QGIS</span></p></body></html>"))
        self.wybor_warstwy.setCurrentText(_translate("WtyczkaProjektDialogBase", "Wybierz warstwę"))
        self.klik_przewyzszenie.setText(_translate("WtyczkaProjektDialogBase", "Oblicz przewyższenie"))
        self.klik_pole.setText(_translate("WtyczkaProjektDialogBase", "Oblicz pole powierzchni"))
        self.label_2punkty.setText(_translate("WtyczkaProjektDialogBase", "Wybierz 2 punkty"))
        self.label_3punkty.setText(_translate("WtyczkaProjektDialogBase", "Wybierz minumum 3 punkty"))
from qgsmaplayercombobox import QgsMapLayerComboBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WtyczkaProjektDialogBase = QtWidgets.QDialog()
    ui = Ui_WtyczkaProjektDialogBase()
    ui.setupUi(WtyczkaProjektDialogBase)
    WtyczkaProjektDialogBase.show()
    sys.exit(app.exec_())
