# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WtyczkaProjektDialog
                                 A QGIS plugin
 1. Liczene przewyższeń  2. Liczenie pola powierzchni metodą Gaussa
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-02
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Nina Janczak Jan Sychowiec
        email                : nina.janczak.stud@pw.edu.pl jan.sychowiec.stud@pw.edu.pl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'wtyczka_projekt_dialog_base.ui'))


class WtyczkaProjektDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(WtyczkaProjektDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.klik_przewyzszenie.cliked.connect(self.wysokosc)
        self.klik_pole.cliked.connect(self.pole)

        def wysokosc(self): 
            liczba_elementów = len(self.wybor_warstwy.currentLayer().selectedFeatures())
            if liczba_elementów == 2: 
                wybrane_elementy = self.wybor_warstwy.currentLayer().selectedFeatures() 
                K=[]
                for element in wybrane_elementy:
                    wsp = element.geometry().asPoint()
                    Z = wsp.z()
                    K.append(Z)
                    roznica_wysokosci=K[0]-K[1]
                self.label_wynik_przewyzszenie.setText(f'{roznica_wysokosci:.3f}')
            elif liczba_elementów < 2:
                self.label_wynik_przewyzszenie.setText("Wybrano za mało punktów")
            elif liczba_elementów > 2:
                self.label_wynik_przewyzszenie.setText("Wybrano za dużo punktów")
        def pole(self):
